-- H2-compatible migration for tests
-- ENUM types not supported in H2; use VARCHAR(20) with DEFAULT 'OFFLINE' instead
-- This file replaces the PostgreSQL-specific V1 migration for test profile

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'OFFLINE',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast username lookup (login queries)
CREATE UNIQUE INDEX idx_users_username ON users (username);
